language: node_js
node_js:
  - "10.17"
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master
before_deploy:
  - ng build --prod
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  local-dir: ./dist
  on:
    branch: master
